steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f',
      'docker/Dockerfile.export',
      '-t',
      'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}',
      '.'
      ]
images: [
  'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${REVISION_ID}'
  ]



