version: '3'
services:
  export:
    build: 
      dockerfile: docker/Dockerfile.export 
      context: .
    environment:
      GCP_BUCKET: finsyn-datastore-exports 
      GCP_PROJECT: insikt-e1887
      GCP_KEYFILE: ./key.json
      GCP_DATASTORE_KIND: shares 
    command: src/export.py
    volumes:
      - ./:/opt/exporter/
